[package]
name = "tokenize_dir_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.98"
proc-macro2 = "^1.0"
quote = "1.0.40"
regex = "1.11.1"
syn = "^2.0"
walkdir = "2.5.0"
